# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
resources:
  repositories:
    - repository: AzureBoardsScript
      ref: master
      type: git
      name: Implementations
steps:
- script: mvn --version
#- task: SynopsysSecurityScan@1
#  inputs:
#    scanType: 'polaris'
#    bridge_polaris_serverUrl: 'https://poc.polaris.synopsys.com'
#    bridge_polaris_accessToken: $(PolarisToken)
#    bridge_polaris_application_name: 'kyleh'
#    bridge_polaris_project_name: 'AzureIssueTest'
#    bridge_polaris_assessment_types: 'SAST,SCA'
#    bridge_polaris_branch_name: '2'
- checkout: AzureBoardsScript
- script: ls AzureBoardsScript
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(Build.SourcesDirectory)/AzureBoardsScript/polaris_azure_ci.py'
    arguments: '--config "polaris-azure.conf" --polaris-application-name "kyleh" --polaris-project-name "AzureIssueTest" --polaris-branch-name Build.SourceBranch --polaris-severities-filter "''''critical'''',''''high'''',''''medium'''',''''low'''',''''info''''" --azure-project-name "PolarisTickets" --azure-iteration-path "iteration 2" --azure-area-path "area path test"'
- script: cat AzureBoardsScript/logs/synopsys-azure.logs
  condition: always()